### ISSUE TITLE
Gallery description does not update if you navigate to another non-adjacent gallery

### ISSUE THREAD

**Issue by ckuper** [dimsemenov/Touchfolio#23]
This is a known bug described at http://support.dimsemenov.com/forums/159023-touchfolio/suggestions/3102387-problem-with-project-description-box and http://support.dimsemenov.com/forums/159023-touchfolio/suggestions/3719785-bug-on-gallery-descriptions-inside-a-gallery-categ.

The problem is this: If the description box for a gallery is open (whether defaulted that way or after clicking it) and you navigate to another gallery within the same category, but NOT the next one or previous one, the description will remain open and keep displaying the old information. If you navigate to an adjacent gallery this description closes/updates properly. I don't know enough javascript to tackle this so I'm looking for help here.

To reproduce:
1. http://christinekuper.com/gallery-category/web-design/
2. Click on the "Facebook App: Samsung Galaxy" link in the lower right corner
3. Click the "wedding: Annie + Ryan" link in the left nav
The description for the Facebook project stays there even when the wedding site is displayed.

I have looked at some other sites from this list http://support.dimsemenov.com/forums/159023-touchfolio/suggestions/3208128-touchfolio-showcase-post-your-site-here-big-lis, and I have not found any yet that do not have this problem.

Thanks for any ideas!
C.

**Comment by ckuper** [comment]
Ok, a friend of mine kindly fixed this bug and gave me a new version of jquery.slider-pack.1.1.min.js, which I uploaded into the /wp-content/themes/dimsemenov-Touchfolio-4a8f617/js folder for my site and presto! What it does is close the project description box when you move to a new project, which allows it to update correctly.

He added this to line 470 (un-minified):

g._cx8();

Hope this helps someone else!

**Comment by karimphoto** [comment]
hi ckuper,

this sounds great, I have the same problem. i would love to know more. should i only add
(un-minified): ?

 What about g._cx8(); ?

thank you,
karim

**Comment by ckuper** [comment]
Hi, Karim,

I have a new baby so it'll take me a little while to get to this--sorry!

Christine

**Comment by ckuper** [comment]
OK, I just looked at this again. The code to add is:

g._cx8();

"(un-minified)" just referred to the fact that the new code was added to
line 470 in the un-minified version of the file. Hope that makes sense.

-- Christine

**Comment by karimphoto** [comment]
Thank you. I give it a try

**Comment by bla166** [comment]
Hi ckuper, 

Thanks for your help. I found your message on http://support.dimsemenov.com/forums/159023-touchfolio/suggestions/3102387-problem-with-project-description-box too. 
But I don't really understand what you did. 

Is the un-minified version is "jquery.slider-pack.js" ? 
So, line 470 is : 
        self._slidesWrapper.bind(self._downEvent, function(e) { self._onDragStart(e); });  
Do I have to add   "g._cx8();"   after this line ? 

It doesn't work for me so I suppose I didn't understand what you mean. Could you explain a little bit for me, or send to me the entire file ? 

I really thank you for your response because, as you said, it is a big problem and I really need to find a solution... And as you saw before, we can't find one on the web. 

Help me... please :-)

**Comment by ckuper** [comment]
Hi,

Sorry I don't understand the code well enough to explain better. I'm going to try attaching a screenshot of a diff between my version of the file and the original. (I used this site http://jsbeautifier.org/ to un-minify the code, and then this one to find the difference: http://www.diffnow.com/) Hope that helps. Otherwise, fell free to contact me at http://christinekuper.com/contact-me/ and I'd be happy to send you my file.
![jqueryslider_fix](https://cloud.githubusercontent.com/assets/4086305/3819775/add8b03c-1cee-11e4-9ec3-04baa8d11f40.png)

Christine

**Comment by bla166** [comment]
For beginners as me, Irene's solution works (on http://support.dimsemenov.com/forums/159023-touchfolio/suggestions/3102387-problem-with-project-description-box), but you need some precision ! 
You have to change as she said, in dimsemenov-Touchfolio>js> jquery.slider-pack.js

« On the unminified version, on line 910 after "self._animateTo(newPos, 'next', 'y', true, inOutEasing);", add the line: "self._hideAlbumInfo();" .

Do it again on line 933. After "self._animateTo(newPos, 'prev', 'y', true, inOutEasing);", add "self._hideAlbumInfo();" »

After that, you have to compress the entire code of "jquery.slider-pack.js" on a website like http://jscompress.com/

Then you copy and paste the code in "jquery.slider-pack.1.1.min.js".

And it works ! Hope this helps someone else !

Thanks a lot Christine !
Sandra

Sandra
