### ISSUE TITLE
WP Less issues

### ISSUE THREAD

**Issue by leandroprz** [dimsemenov/Touchfolio#60]
**Edit**: turns out somehow my PHP version got changed on my hosting and that was causing the issue. Sorry about this.

I'm getting this error, not sure since when (probably after some WordPress update).

`[22-Aug-2016 15:58:52 UTC] PHP Warning:  filemtime(): stat failed for /home/******_/public_html/wp-contenthttps://leandroperez.com.ar/wp-content/themes/touchfolio/style-touchfolio-modificado.less in /home/**_***_/wp-content/themes/touchfolio/inc/plugins/wp-less/lib/Stylesheet.class.php on line 96
[22-Aug-2016 15:58:52 UTC] PHP Fatal error:  Uncaught exception 'Exception' with message 'load error: failed to find /home/**_***_/wp-contenthttps://leandroperez.com.ar/wp-content/themes/touchfolio/style-touchfolio-modificado.less' in /home/**_****/wp-content/themes/touchfolio/inc/plugins/wp-less/lib/vendor/lessphp/lessc.inc.php:1927
Stack trace:
#0 /home/******_/wp-content/themes/touchfolio/inc/plugins/wp-less/lib/Compiler.class.php(24): lessc->__construct('/home/**_****/...')
#1 /home/******_/wp-content/themes/touchfolio/inc/plugins/wp-less/lib/Plugin.class.php(122): WPLessCompiler->__construct('/home/**_****/...')
#2 /home/*******/wp-content/themes/touchfolio/inc/plugins/wp-less/lib/Plugin.class.php(161): WPLessPlugin->processStylesheet('style', false)
#3 [internal function]: WPLessPlugin->processStylesheets()
#4 /home/*******/wp-includes/plugin.php(600): call_user_func_array(Array, Array)
#5 /home/******_/wp-includes/class-wp.php(738): do_action_ref_array('w in /home/**_****/wp-content/themes/touchfolio/inc/plugins/wp-less/lib/vendor/lessphp/lessc.inc.php on line 1927`

Is there a way to fix this?

Thank you

**Comment by CryssDOTnet** [comment]
Hi. Try my fix I posted shortly before.

https://github.com/dimsemenov/Touchfolio/issues/60
