### ISSUE TITLE
SOLVED: theme works only with https/SSL or http but not both

### ISSUE THREAD

**Issue by CryssDOTnet** [dimsemenov/Touchfolio#62]
Maybe someone else runs into this specific problem.

In short, try this:
-     Switch from http to https on both variables in your wordpress configuration
-     Install the WP-Less plugin. It's a more recent version than the version that is delivered with Touchfolio. That threw me another error about a not defined variable: @menu-font-color (E.g. @menu-font-color: #999;)

So I defined it in style-touchfolio-default.less an voilá, my site is available via https and http

Long story: I recently installed the old Touchfolio theme for Wordpress and ran into one problem. The site was only available without SSL. After two days I told wordpress to be accessible via https set the two URL variables. Now the site was accessible via SSL, BUT http didn't work anymore. The result was the same white screen as before the change. So I dug into it deeper, turned debug on and found out there was some problem with the lesscompiler (whatever that is ...) and googled the error message to find out there is a WP-Less plugin. So I installed it and after another error message (above) I finally solved my problem and it saved me three days of polishing the theme to my liking. Pew!

I hope that little blog entry might help someone someday!

From my Blog:
http://cryss.net/post/touchfolio-wordpress-theme-only-with-https-ssl-or-http

**Comment by CryssDOTnet** [comment]
I am curious about what the underlying problem is but also happy that I can use this awesome theme. Hope someday there will be an updated version!

**Comment by federicomaffei** [comment]
Stumbled onto this while researching this same esoteric error and fixed it in a few seconds: thanks! 👍

**Comment by Simtey** [comment]
Hi everybody,

I tried but it seems that I can't solve the issue alone. I'm a noob in development but I'm more than interested to learn the basis.
 When I want to make my site working in https I got some issues :
- I tried to install a more recent version of the WP-Less plugin but I got some errors too.
- I also tried to directly install the files provided by geraldo but it does not work too.

So I copied back to the old original wp-less library and php files of the latest original touchfolio theme.

here are the error I got :

Warning: filemtime(): stat failed for /home/users5/s/sthery/www/wp-contenthttp://www.simonthery.fr/wp-content/themes/Touchfolio/style-touchfolio-default.less in /home/users5/s/sthery/www/wp-content/themes/Touchfolio/inc/plugins/wp-less/lib/Stylesheet.class.php on line 96

Fatal error: Uncaught Exception: load error: failed to find /home/users5/s/sthery/www/wp-contenthttp://www.simonthery.fr/wp-content/themes/Touchfolio/style-touchfolio-default.less in /home/users5/s/sthery/www/wp-content/themes/Touchfolio/inc/plugins/wp-less/lib/vendor/lessphp/lessc.inc.php:1927 Stack trace: #0 /home/users5/s/sthery/www/wp-content/themes/Touchfolio/inc/plugins/wp-less/lib/Compiler.class.php(24): lessc->__construct('/home/users5/s/...') #1 /home/users5/s/sthery/www/wp-content/themes/Touchfolio/inc/plugins/wp-less/lib/Plugin.class.php(122): WPLessCompiler->__construct('/home/users5/s/...') #2 /home/users5/s/sthery/www/wp-content/themes/Touchfolio/inc/plugins/wp-less/lib/Plugin.class.php(161): WPLessPlugin->processStylesheet('style', false) #3 /home/users5/s/sthery/www/wp-includes/class-wp-hook.php(286): WPLessPlugin->processStylesheets() #4 /home/users5/s/sthery/www/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array) #5 /home/users5/s/sthery/www/wp-includes/plugin.php(544): WP_Hook->do_ac in /home/users5/s/sthery/www/wp-content/themes/Touchfolio/inc/plugins/wp-less/lib/vendor/lessphp/lessc.inc.php on line 1927


Can someone help me to understand the issue and to fix it ?
Thanks, and overall thank you so much for all the help provided to keep this nice Touchfolio theme alive :).
