### ISSUE TITLE
…

### ISSUE THREAD

**Issue by glueckpress** [dimsemenov/Touchfolio#8]
…

**Comment by naires** [comment]
Hi Glueckpress,

Do you have any developments from the issue you posted here:

"I’ve added an extra div for the current image’s info fields provided by WordPress. (You know, title, description etc. in the Media Screen…) Got all data in the markup, just don’t see where to bind my jQuery function so it gets called when the image changes. 
Is there any callback I can use? Or do I bind my function to the mousedown event?

Some background:
I’ve hacked my way through content-ds-gallery.php to add the native WordPress title and description fields for images. Essentially it’s 3 lines of code:

$my_attachment_title = esc_html( get_post($attachment_id_item)->post_title );
$my_attachment_content = esc_html( get_post($attachment_id_item)->post_content );
$my_attachment_excerpt = esc_html( get_post($attachment_id_item)->post_excerpt );
Plus 3 extra data- attributes for list elements in div.slider-data:

$album_data .= "\t\t<li class=\"two-dim-item\"{$video_data}{$img_scale}";
$album_data .= " data-img-width=\"{$image_widths[$j]}\" data-img-height=\"{$image_heights[$j]}\"";
$album_data .= " data-img-posttitle=\"{$my_attachment_title}\"";
$album_data .= " data-img-postexcerpt=\"{$my_attachment_content}\"";
$album_data .= " data-img-postcontent=\"{$my_attachment_excerpt}\"";
$album_data .= " ><a href=\"{$image_urls[$j]}\">{$alt_attr}</a>";
$album_data .=  "</li>\n";
Now I've got everything I need right there in my Markup, and the initial image has some fine extra info to it put together from the list item with the image’s data in it.
Only the jQuery fumbler I am isn’t expert enough to comprehend on what event I have to bind my function to have it called when the image changes?

Any chance for a quick tip? Thanks a bunch!"

**Comment by glueckpress** [comment]
Hi Nelson,
other than the code you posted here: no, I don’t. I was co-working on a friend’s client project. Both of us finally gave up, because we were not Javascript wizards enough to so understand your script that we would have been able to hack it. ;) As I said, I easily got the additional markup put out, but failed to make it change dynamically according to the image being displayed. 

My friend’s client probably would still love that feature, though, as probably many photographers would when they use the theme. I'll notify my friend of this dialogue so he can get in touch with you if you don't mind?

**Comment by naires** [comment]
Hi,

Unfortunately i'm not also a javascript wizard :( but i will try to put working the code that you have started...

best,
nelson

p.s by the way, the script is not mine. The original author is dimsemenov :)

**Comment by naires** [comment]
Do you have a fork of Touchfolio to see your modifications? If not, can you put in github the complete "hacked" file: content-ds-gallery.php 

Thanks,

**Comment by glueckpress** [comment]
I'll put up a fork.
